### ISSUE TITLE
Runbook fails with 400 bad request

### ISSUE THREAD

**Issue by ralpje** [printix/Power-BI#1]
Hi,

After setting up the prereqs as detailed in the README I try to run the data collection script through the runbook, but receive a '400 Bad Request' error, and no data is collected. Detailed information (I did some minor edits for privacy reasons):

```
Exception: Microsoft.PowerShell.Commands.WriteErrorException: Exception: The remote server returned an error: (400) Bad Request. Printix Request ID: 4d83ddca-ad5f-4f73-819d-d215609ab6fc Uri: [] or [https://api.printix.net/tenants/XXXX/dataextract?page=0&pageSize=10] Body: [{
 "blobStoreAccountName": "foo",
 "from": "2018-05-05T01:02:21.0845493Z",
 "to": "2018-07-04T01:02:21.1001746Z",
 "blobStoreAccountKey": null,
 "extracts": [
 "NETWORKS",
 "TRACKING_DATA",
 "JOBS",
 "PRINTERS",
 "DEVICE_READINGS",
 "USERS",
 "WORKSTATIONS"
 ]
 }] Response: System.Net.HttpWebResponse Activity: Write-Error Error Category: NotSpecified Error Reason: WriteErrorException ( Exception: Microsoft.PowerShell.Commands.WriteErrorException: Exception: The remote server returned an error: (400) Bad Request. Printix Request ID: 4d83ddca-ad5f-4f73-819d-d215609ab6fc Uri: [] or [https://api.printix.net/tenants/XXXX/dataextract?page=0&pageSize=10] Body: [{
 "blobStoreAccountName": "foo",
 "from": "2018-05-05T01:02:21.0845493Z",
 "to": "2018-07-04T01:02:21.1001746Z",
 "blobStoreAccountKey": null,
 "extracts": [
 "NETWORKS",
 "TRACKING_DATA",
```

The output logged from the runbook:

```
01:02:17 - Successfuly connected to Azure with Service Principal.
01:02:18 - Getting AutomationPSCredential [XXX-creds].
01:02:18 - Printix API entry [https://api.printix.net/public/partners/XXXX].
01:02:20 - Working on Partner account [COMPANYNAME] email [EMAIL]
01:02:20 - Found [] tenants
01:02:20 - After filtering out tenants not found in storagemapping, continuing to work on [] tenants
01:02:20 - Working on tenant [COMPANY] tenantdomain [COMPANY.printix.net]
01:02:20 -   Requesting data extract. This might take some time...
```

After this no extra information is logged. Can someone point me in the right direction for solving this problem?

**Comment by MortenRei** [comment]
Hi @ralpje 

That's an interesting one. On line 65 in the "Get-PrintixDataExtract.ps1" could you change the VerbosePreference  to "Continue" and post the output?

Could you also ensure that all the values in the $StorageMapping object is in lowercase? I suspect that the 400 bad request might be because of something like that. If that fixes your problem, I'll update the script to ensure all values automatically get converted to lower case.

**Comment by ralpje** [comment]
Hi MortenRei,

Thanks :) 
The VerbosePreference was already set to Continue. Only the resourcegroup was with some capital letters. Fixed that, but to no avail. The error message remains the same.

**Comment by MortenRei** [comment]
@ralpje, I talked with Printix, and it seems like the 'blobStoreAccountKey' is actually empty. Just to confirm it, I also managed to reproduce the error you got by sending in an empty BlobStorageAccountKey. I was just assuming that you had manually removed the actual 'BlobStoreAccountKey' from the output above, but then it was actually Null.

What kind of Storage Account have you created? Blob Storage og General Purpose (V1 or V2)?

Basically the code that extracts the Storage account key and sends it to Printix is pretty straight forward (Line 193 in Printix.psm1);
#Get blob storage key
        $StorageAccountPrintixExtractedDataKey = (Get-AzureRmStorageaccountKey -Name $StorageMapping.StorageAccountPrintixExtractedData -ResourceGroupName $StorageMapping.StorageAccountPrintixExtractedDataResourceGroup)[0].value
 
Let's find out wants wrong, and get you up and running. That will also allow us to update the code, and make it handle cases like yours, so others don't end up with the same problem.

**Comment by ralpje** [comment]
Hi,

Just to confirm: I indeed did not manually remove the blobStoreAccountKey, it is actually Null.
I didn't create the storage account myself, but on investigation it is indeed a General Purpose (v1) storage, with in it a blob storage service with the container. I don't have the actual rights on the resource group to create a new storage account as blob storage, so I'll have one of my colleagues do this to check if this resolves the issue. 

For what is worth: I am able to extract the storage account keys from this storage account through powershell:
`Get-AzureRmStorageAccountKey -ResourceGroupName resourcegroup -Name storageaccountname`
does actually return both keys.

**Comment by MortenRei** [comment]
It should not really matter if you have V1 or V2 general purpose storage. It works on both version.
Did you run that command from your own computer, or from the Automation account test pane when you got the account keys returned? 

Is the Azure Run As Account correctly configured and given the appropriate role? If yes, could you run the runbook again with $DebugPreference = "Continue", and post the relevant data from the Get-AzureRMStorageAccountKey command?

**Comment by ralpje** [comment]
Hi @MortenRei,

It turns out this is a problem with the AzureRM.Storage module used within the Azure Automation account. After some fiddling around I decided to run an update of the Azure module within the Azure Automation account which updated the AzureRM.Storage module to 5.0.0. After that, the runbook works like a charm.
Thanks for assisting!

**Comment by MortenRei** [comment]
Glad you figured it out. I just pushed a new commit , that improves the error handling for similar cases and updated the documentation with a basic troubleshooting guide.
