### ISSUE TITLE
Errors in device_readings

### ISSUE THREAD

**Issue by Jakuzza** [printix/Power-BI#10]
Getting "Errors in device_readings" when doing a refresh. Looks like the "detected_errors_states" column isn't working for some reason. Error states "Expression.Error: The parameter is expected to be of type Text.Type or Binary.Type." I was assuming it was the values "null", but changing them to "none" did not resolve the issue.

**Comment by MortenRei** [comment]
Hi @Jakuzza 

I've identified the vault in way JSON is parsed for the "detected_errors_state" column. I'll publish a fix in a couple of days.

**Comment by MortenRei** [comment]
@Jakuzza this should now be fixed in the latest V1.1.0 release. Could you please confirm with your dataset?

**Comment by Jakuzza** [comment]
Yes. I can confirm that this has been fixed for my report. Thanks!

**Comment by MortenRei** [comment]
@Jakuzza Perfect! I'll go ahead and close this issue then. Thanks for the bug report :)
