### ISSUE TITLE
Request: different filters

### ISSUE THREAD

**Issue by ChorusMark** [printix/Power-BI#16]
Hi,

In common with a lot of our clients, we have 2 types of printers, a handful that are internally owned (smaller) devices. And a handful of large MFD's that are 3rd party supplied.

Your new Power BI report which includes department is great, but on that page we also need to be able to filter the data by Dept, Printer, and B&W or Colour printing pages. 

The reason is that most 3rd party contracts are based on a price per page (one price for B&W, one price for colour). But if we cannot get Printix to tell us what the split of page counts is for specific printers, by department, by page type (B&W, colour) then we cannot recharge effectively internally within the business via Printix.

Would that be possible?

Thanks

**Comment by MortenRei** [comment]
Hi @ChorusMark 

Great idea! You're basically asking for a page that could be used to calculate the cost., right? That shouldn't be too difficult to accomplish. 

How would you like a page like that to work? Setting your own values per printer, or just a general price per page for Color VS B&W? What about markup's etc?

**Comment by ChorusMark** [comment]
Hi Morten,

Thanks for the quick reply.

I'm not sure it needs costs.

Its basically a page that starts with a filter for selecting one or more printers, once the printer (s) are selected then below shows:

                  B&W      Colour
Dept A        500          100
Dept B         250           50

etc.. 

This would enable the finance teams to recharge internally against a single supplier invoice.

Does that make sense?

Thanks!

**Comment by MortenRei** [comment]
Hi  @ChorusMark 

We are actually working on something like this, that will be released with the next version of the Power BI report. Hopefully it will give you what you need!

**Comment by MortenRei** [comment]
Hi @ChorusMark 

This should now be added to the report in the latest release https://github.com/printix/Power-BI/releases.

I'm therefor closing this request.

**Comment by ChorusMark** [comment]
Thats great, thank you @MortenRei
