### ISSUE TITLE
Alerts

### ISSUE THREAD

**Issue by bleek00** [printix/Power-BI#17]
Hi,
I integrated power-bi with printix, all works fine. how can I set an alert for low paper / ink or any other reported errors on the printers?

**Comment by MortenRei** [comment]
Hi @bleek00 

Sorry for the late answer. Have you checked out Power BI Alerts; https://docs.microsoft.com/en-us/power-bi/service-set-data-alerts 

Haven't done any testing on your specific case, but it should be fully doable if you create some new visuals that's specific to what your asking for!

**Comment by MortenRei** [comment]
Closing this issue as the solution has been provided in my last comment. If you need anything more advanced than this, I would suggest that you check out Printix's official API.
