### ISSUE TITLE
[Feature Request] Dark Mode

### ISSUE THREAD

**Issue by o-l-a-v** [printix/Power-BI#18]
I love that the Printix dashboard can save trees. It would be even greater if it could save power consumption too, by adding dark mode. :)

**Comment by MortenRei** [comment]
Hi

There is loads of different dark themes available on the Power BI themes gallery that you can use to switch themes in the report.

Themes gallery; https://community.powerbi.com/t5/Themes-Gallery/bd-p/ThemesGallery
How to switch; https://docs.microsoft.com/en-us/power-bi/desktop-report-themes
