### ISSUE TITLE
Multi-tenant Printix configuration

### ISSUE THREAD

**Issue by mauszozo** [printix/Power-BI#20]
Anyone have a good solution for working with this Power BI template in a multi-tenant Printix setup?

We're just using the Printix created databases. When you have Printix create the database it gives every tenant the exact same database server address (printix-bi-data-2.database.windows.net), exact same port number (1433), and the exact same database name (printix_bi_data_2_1). So in Power BI, you can only list the data source for one tenant since it doesn’t understand that we’re using the same server, port, and database name for multiple different tenant data sets. So when I open the Power BI file I have to wait for it finish refreshing all the data, then go in to Data Sources -> Edit Permissions -> Edit Credentials, enter the credentials for the tenant I want to view, then wait for it to refresh all the data again.

Is there a better way?  I talked to Printix support and they suggested hosting my own database server so I could control the database name.  It's too bad they didn't use the tenant GUID as part of the database name like they do for the username.

**Comment by gregvinyard** [comment]
If you have a Power BI Pro license you can create multiple workspaces online, one for each tenant, each with their own data source.  You can also set them to automatically refresh on a schedule.  This does not help with the Power BI desktop client, but it does work well if you have the Pro license for the online version.

**Comment by Damien-Printix** [comment]
We are currently not pursuing changing the data model. Maybe the suggestion by @gregvinyard helps?
I will close this request now.
