### ISSUE TITLE
Warnings for Tracking_data and Device_readings

### ISSUE THREAD

**Issue by PatrickMorandi** [printix/Power-BI#4]
Hi

I Have the following Warnings

‎‎8‎/‎30‎/‎2018‎ ‎8‎:‎54‎:‎51‎ ‎AM | Warning | 06:54:51 -              [TRACKING_DATA] does not seem to have any content. Skipping file

‎8‎/‎30‎/‎2018‎ ‎8‎:‎54‎:‎51‎ ‎AM | Warning | 06:54:51 -              [DEVICE_READINGS] does not seem to have any content. Skipping file

because this data is not extracted, the report does not work in Power BI,  i get an error the data is not found.

For This Reason the configuration to the new Datasource in Power BI fails.

Regards Patrick

**Comment by MortenRei** [comment]
Hi @PatrickMorandi 

I'm closing this one as a duplicate to issue #3 . 
Thank you for pointing out the lower case invariant problem. I'll fix the issue as soon as possible and publish a fix to the runbooks.
