### ISSUE TITLE
Data Source for Power BI

### ISSUE THREAD

**Issue by PatrickMorandi** [printix/Power-BI#5]
Hi

It's Looks Like that the Queries in Power BI are case sensitive.

DataSource.Error: AzureBlobs failed to get contents from 'https://printix.blob.core.windows.net/dashboard/jobs/jobs.json'. Status code: 404, description: 'The specified blob does not exist.'.
Details:
    DataSourceKind=AzureBlobs
    DataSourcePath=https://printix.blob.core.windows.net/dashboard
    Url=https://printix.blob.core.windows.net/dashboard/jobs/jobs.json

After renaming of json files and folder in to lower case on the Blob storage the queries are working.

Regards Patrick

**Comment by MortenRei** [comment]
Hi @PatrickMorandi 

I'm closing this one as a duplicate to issue #3 . 
Thank you for pointing out the lower case invariant problem. I'll fix the issue as soon as possible and publish a fix to the runbooks.
