### ISSUE TITLE
PrintixPowerBIDesign

### ISSUE THREAD

**Issue by PatrickMorandi** [printix/Power-BI#6]
Hi

Can you upload the newest PrintixPowerBIDesign Pictures.

Thanks
Patrick

**Comment by MortenRei** [comment]
Hi @PatrickMorandi 

You can find any element used in the PowerBI report in the repo.

- Fonts; https://github.com/printix/Power-BI/tree/master/Fonts/fonts
- Powerpoint; https://github.com/printix/Power-BI/tree/master/PowerPoint
- Images; https://github.com/printix/Power-BI/tree/master/Images

The PowerPoint contains all graphics used in the Power BI template. An export of the PowerPoint design can also be found here; https://github.com/printix/Power-BI/tree/master/Images/PowerPoint/PrintixPowerBIDesign 

:)

**Comment by PatrickMorandi** [comment]
that's OK

Thanks
