### ISSUE TITLE
403 FOrbidden error on test

### ISSUE THREAD

**Issue by KeithMoonWestmount** [printix/Power-BI#7]
Hello, hopefully someone can shed a little light on the situation, when I run the test i receive

Exception: Microsoft.PowerShell.Commands.WriteErrorException: Exception: The remote server returned an error: (403) Forbidden. 

and 

Activity: Write-Error 
Error Category: NotSpecified 
Error Reason: WriteErrorException ( 
Exception: Microsoft.PowerShell.Commands.WriteErrorException: Exception: The remote server returned an error: (403) Forbidden. 

I think the issue is with accessing my blob storage, am I on the right track?

**Comment by MortenRei** [comment]
Hi @KeithMoonWestmount 

Could you please post more of the output? There is several parts of the code that could return to an 403.

**Comment by KeithMoonWestmount** [comment]
@MortenRei thanks for your quick response, as per below, hope this helps.

`
Failed
 
Exception: Microsoft.PowerShell.Commands.WriteErrorException: Exception: The remote server returned an error: (403) Forbidden. 
Printix Request ID: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx 
Uri: [] or [https://api.printix.net/tenants/xxxxxx-xxxx-xxxx-xxxx-xxxxxxx/dataextract] 
Body: [{
    "blobStoreAccountName":  "xxxxxxxx",
    "from":  "2018-09-04T04:04:39.6893138Z",
    "to":  "2018-09-10T04:04:39.7205211Z",
    "blobStoreAccountKey":  "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "extracts":  [
                     "NETWORKS",
                     "TRACKING_DATA",
                     "JOBS",
                     "PRINTERS",
                     "DEVICE_READINGS",
                     "USERS",
                     "WORKSTATIONS"
                 ]
}] 
Response: System.Net.HttpWebResponse 
 
Activity: Write-Error 
Error Category: NotSpecified 
Error Reason: WriteErrorException ( 
Exception: Microsoft.PowerShell.Commands.WriteErrorException: Exception: The remote server returned an error: (403) Forbidden. 
Printix Request ID: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx 
Uri: [] or [https://api.printix.net/tenants/xxxxxxxxxxxxxxxxxxxxxxx/dataextract] 
Body: [{
    "blobStoreAccountName":  "xxxxxxxxx",
    "from":  "2018-09-04T04:04:39.6893138Z",
    "to":  "2018-09-10T04:04:39.7205211Z",
    "blobStoreAccountKey":  "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "extracts":  [
                     "NETWORKS",
                     "TRACKING_DATA",
                     "JOBS",
                     "PRINTERS",
                     "DEVICE_READINGS",
                     "USERS",
                     "WORKSTATIONS"
                 ]
}] 
Response: System.Net.HttpWebResponse 
 
Activity: Write-Error 
Error Category: NotSpecified 
Error Reason: WriteErrorException)
`

**Comment by MortenRei** [comment]
@KeithMoonWestmount , I think that could be one of two reason;

**If you run the direct customer runbook;**
1) Please verify the following;

- Double check that the 'ClientCredentialsName' you provided is actual correct, and that the username and PW reflects the values you got from Printix.
-  Double check that the 'TenantDomain' property in the $StorageMapping object reflects the Printix tenant that your API credentials are for.

**If you run the partner runbook**
1) Verify the StorageAccount (it's case sensitive) property in the $StorageMapping object.

- If it continues to fail, you will need help from Printix directly. Could you send the error including the 'Printix Request ID' (Important!) to support@printix.net? They will be able to give you a more specific error.

Please keep us updated on either results :)

**Comment by KeithMoonWestmount** [comment]
Hello Peter,

Getting so close to working now.
I can see data in the blob as per below screenshot
[cid:image002.png@01D45A44.A20D3EC0]

When I refresh my dataset in powerBI, I get different errors each time I try.  Like below.

Something went wrong
There was an error when processing the data in the dataset.
Please try again later or contact support. If you contact support, please provide these details.
Message: AzureBlobs failed to get contents from 'https://printixwmpbi.blob.core.windows.net/westmountprintix/printers/printers.json'. Status code: 404, description: 'The specified blob does not exist.'. Table: Printers_PDLS.
Cluster URI: WABI-SOUTH-EAST-ASIA-redirect.analysis.windows.net

Something went wrong
There was an error when processing the data in the dataset.
Please try again later or contact support. If you contact support, please provide these details.
Message: AzureBlobs failed to get contents from 'https://printixwmpbi.blob.core.windows.net/westmountprintix/users/users.json'. Status code: 404, description: 'The specified blob does not exist.'. Table: Users.
Cluster URI: WABI-SOUTH-EAST-ASIA-redirect.analysis.windows.net



Kind regards

Keith Moon Systems Administrator | Westmount Education

**Comment by MortenRei** [comment]
@KeithMoonWestmount , we can't see the image you tried to attached. 

Basically, there could be a couple of different errors;
1. It seems like you entered an invalid blob storage. Could you please double check your URI. Please note that the URI is casesensitive. 
2. Could you please verify that the printers/printers.json and users/users.json actually exists, and that they have content?

**Comment by KeithMoonWestmount** [comment]
Hello,

Thanks for your reply.

I can see the blob storage through azure storage explorer, I can see 5 folders inside the blob, each folder contains a .json file.  Our data is within these files.

I notice with the example data there are 7 folders each with a .json file.
I am not receiving  device readings and tracking data folders and associated .json files.

I am using the click to copy buttons to copy all required information.

The error I have now is this.

Something went wrong
There was an error when processing the data in the dataset.
Please try again later or contact support. If you contact support, please provide these details.
Message: AzureBlobs failed to get contents from 'https://printixwmpbi.blob.core.windows.net/westmountprintix/printers/queues.json'. Status code: 404, description: 'The specified blob does not exist.'. Table: Queues_details.
Cluster URI: WABI-SOUTH-EAST-ASIA-redirect.analysis.windows.net
Activity ID: 2ba69ca7-3380-48e6-b2b1-ed2830e23ddb
Request ID: 94c18374-bf79-9926-3ec4-06ce11497239
Time: 2018-10-02 20:30:53Z

There is no queues .json file in the printers folder, only a printers.json

I don’t think all the data is coming from Printix.




Kind regards

Keith Moon Systems Administrator | Westmount Education

**Comment by KeithMoonWestmount** [comment]
Adding to the previous reply.
I have two warnings when I run the data extract.

[TRACKING_DATA] does not seem to have any content. Skipping file

[DEVICE_READINGS] does not seem to have any content. Skipping file

03/10/2018, 10:02:03

Progress

Set-AzureStorageBlobContent task status :

03/10/2018, 10:02:03

Output

21:02:03 - Getting Azure Storage Blob Content from cludblob [device-readings.zip]

03/10/2018, 10:02:03

Progress

Get-AzureStorageBlobContent task status :

03/10/2018, 10:02:03

Progress

Download blob 'device-readings.zip' into 'C:\Users\Client\Temp\DEVICE_READINGS.zip'.

03/10/2018, 10:02:03

Progress

Get-AzureStorageBlobContent task status :

03/10/2018, 10:02:04

Progress

Download blob 'device-readings.zip' into 'C:\Users\Client\Temp\DEVICE_READINGS.zip'.

03/10/2018, 10:02:04

Output

21:02:04 - Unzipping file [C:\Users\Client\Temp\DEVICE_READINGS.zip]

03/10/2018, 10:02:04

Progress

Expand-Archive

03/10/2018, 10:02:04

Progress

Expand-Archive

03/10/2018, 10:02:04

Progress

Expand-Archive

03/10/2018, 10:02:04

Warning

21:02:04 - [DEVICE_READINGS] does not seem to have any content. Skipping file



Does this matter?



Kind regards

Keith Moon Systems Administrator | Westmount Education

**Comment by MortenRei** [comment]
Perfect, that helps. 

Two questions;
1) Do you have the latest Automation code ? There was a serious bug in an eralier version that could lead to that fault. If not, please update to the latest module and runbook.
2) This could also happen if you have never printed anything with Printix. Then there won't be any data in those files. If this is the case, go and print something and try again :) 

If the latter is the problem, i'm not sure how we can avoid the problem in the future. Basically it's just a problem the very first time you do an extract and where those files are empty. The PowerBI dashboard needs data in each file to actually work, else it will just display the errors you saw. If you first have a successfull export, it does not matter if the files are empty the next time you try to do an export, as it won't overwrite any files if the export is empty.

**Comment by vruum** [comment]
Hi Keith

In Addition to what Morten said,if you know you have print activity, it could also be interesting to set the number of days you export for as low as meaningfully possible (a couple of days?).

**Comment by KeithMoonWestmount** [comment]
Hello all,
I have updated the files, yes I was on the 1.08 now 1.09  I believe.  The

However

I have a new error ☹

Something went wrong
There was an error when processing the data in the dataset.
Please try again later or contact support. If you contact support, please provide these details.
Data source error: Column 'Queues.queueId' in Table 'Queues_details' contains a duplicate value '187c8f6e-f0f4-48cf-915b-4dc5eab62384' and this is not allowed for columns on the one side of a many-to-one relationship or for columns that are used as the primary key of a table. Table: Queues_details.
Cluster URI: WABI-SOUTH-EAST-ASIA-redirect.analysis.windows.net
Activity ID: 574d6887-355d-4f41-be7f-1441059cb407
Request ID: fdb1e56d-dac6-963f-c011-0aa49c670a54
Time: 2018-10-03 21:24:57Z

It must be very close to working now.


Kind regards

Keith Moon Systems Administrator | Westmount Education

**Comment by KeithMoonWestmount** [comment]
I believe I have it all working now, thanks for your assistance in getting this resolved.
